# src/main/resources/upload-config.yml
upload:
  categories:
    product:
      dir: products
      max-size: 5MB
      sizes:
        - name: large
          width: 800
          height: 600
        - name: medium
          width: 400
          height: 300
        - name: small
          width: 200
          height: 150

    avatar:
      dir: avatars
      max-size: 2MB
      sizes:
        - name: large
          width: 200
          height: 200
        - name: small
          width: 80
          height: 80

    banner:
      dir: banners
      max-size: 5MB
      sizes:
        - name: desktop
          width: 1920
          height: 400
        - name: mobile
          width: 750
          height: 300
